apiVersion: v1
baseDomain: ocp.devenchoice.org
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: 
    azure:
      osDisk:
      type: Standard_D2s_v4
      zones:
      - "1"
      - "2"
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      osDisk:
      type: Standard_D4s_v4
      zones:
      - "1"
      - "2"
      - "3"
  replicas: 3
metadata:
  creationTimestamp: null
  name: vitek
networking:
  clusterNetwork:
  - cidr: 10.16.64.0/19
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.16.112.0/20
  networkType: OpenShiftSDN
  serviceNetwork:
  - 10.16.96.0/20
platform:
  azure:
    cloudName: AzurePublicCloud
    region: eastus
    baseDomainResourceGroupName: vitek-rg
    networkResourceGroupName: vitek-rg
    virtualNetwork: vitek-vnet
    controlPlaneSubnet: masters
    computeSubnet: workers
    outboundType: Loadbalancer
publish: Internal
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYjBiNWRlOGVjMDdjNDE5MWI0ODE0MTk4MjgzMWE4MWU6SFVTSExER1UwVFg1TDlOWDg3UlFGNTJXQkhLUDUwTVJDUFVPWDFVWVEzUVhZQzVCRVE2NUpQSkdXRExUNEY3Uw==","email":"dseucan@enchoice.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYjBiNWRlOGVjMDdjNDE5MWI0ODE0MTk4MjgzMWE4MWU6SFVTSExER1UwVFg1TDlOWDg3UlFGNTJXQkhLUDUwTVJDUFVPWDFVWVEzUVhZQzVCRVE2NUpQSkdXRExUNEY3Uw==","email":"dseucan@enchoice.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWM1MDYwYjY0LWQ5YzYtNGIxYS1hMzU0LTE4ZTljZGNjZDY3NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTRPVEV3WkRNNU1tTTBaVGcwWWpBellUWmtNRFZtTURnMU1ERTVZVEZtWVNKOS5rckpaN2xseDZCNnVyMmFKRVVNUjBKamw3c19qTl9rZDE4Yk53RTh0b0ZKTTJZZUFIVG5iLWNXUFJBWW96X2hIU0ZHVi1JMzBXSzlibkFOZlZXZ056NW9rbXhVbTBta0FzYWQ5dXBXa1BrMkEtX1dxeUc2X0JRTTNzS2xPeno3Z0wtSU9GQldUZWE2Rl9ka2NqblB0QWpkQjVVTjhUSmFtdmQzbHB3YkNnXzhPMXdNSnZDMUZpZWYycjg0THVzcUJzYWdka0I0RV9vaTRYZDE1Z3o3MmJ0ZnZoN2FlRVlZWmExT1NJYkkxNzdNU3ZCbVRHeFRPY1FqTjc1MWpLUkdpd2Z2X3lYLUdjNFpVM2VHa0c1eEI3Vm43TVUzaVF2SUxzT0p3d0d4ZVp3eUt1NG1YMnZmX05rWVlGekR6NGQxUjhrcm5MN0hUbmIwemZpSHEya2YxckRPRU9CZlFublc1Y3Y1ZG9XVm5POERHamVJZVdSTTNMYUpuNm9NTXRHVzgyVkdFOE5OQlpkTWxMVGVNUU16Vk9WYWMzSzFxdzduOWZiN21faVVLdE5XeGJleW94UHN6ZnoySEF5TXVMeEZRYW1jaTFMU0ZlM1Y0S3M3ZVJWRWtUbWJ1NktzWmtWMlp3RTBXN0puaHBOUDNCM3ZSYThNcmJvS2FOMWtocjhfYlJUMXg3R2dJUWFqT0NKdDJZaHV3VjA0M2lyX1FrV3cya01CUVJfS3FNZkstMHZaQ0QxcWV3SnNTSU5PbERYVEFkU01KV3EyY1JBNHVGdHRKdjY0bUxHazdUandUd3RLbFJzd2hDMWVkV3k3WDBfWE11MUVkLXEzYlF5Q29US1RDUnh0bmw3eWI0Mno1YXlCTmZFUWZiTHJKNHpRbnRUaHlQRjliQWx6SlJwMA==","email":"dseucan@enchoice.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWM1MDYwYjY0LWQ5YzYtNGIxYS1hMzU0LTE4ZTljZGNjZDY3NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTRPVEV3WkRNNU1tTTBaVGcwWWpBellUWmtNRFZtTURnMU1ERTVZVEZtWVNKOS5rckpaN2xseDZCNnVyMmFKRVVNUjBKamw3c19qTl9rZDE4Yk53RTh0b0ZKTTJZZUFIVG5iLWNXUFJBWW96X2hIU0ZHVi1JMzBXSzlibkFOZlZXZ056NW9rbXhVbTBta0FzYWQ5dXBXa1BrMkEtX1dxeUc2X0JRTTNzS2xPeno3Z0wtSU9GQldUZWE2Rl9ka2NqblB0QWpkQjVVTjhUSmFtdmQzbHB3YkNnXzhPMXdNSnZDMUZpZWYycjg0THVzcUJzYWdka0I0RV9vaTRYZDE1Z3o3MmJ0ZnZoN2FlRVlZWmExT1NJYkkxNzdNU3ZCbVRHeFRPY1FqTjc1MWpLUkdpd2Z2X3lYLUdjNFpVM2VHa0c1eEI3Vm43TVUzaVF2SUxzT0p3d0d4ZVp3eUt1NG1YMnZmX05rWVlGekR6NGQxUjhrcm5MN0hUbmIwemZpSHEya2YxckRPRU9CZlFublc1Y3Y1ZG9XVm5POERHamVJZVdSTTNMYUpuNm9NTXRHVzgyVkdFOE5OQlpkTWxMVGVNUU16Vk9WYWMzSzFxdzduOWZiN21faVVLdE5XeGJleW94UHN6ZnoySEF5TXVMeEZRYW1jaTFMU0ZlM1Y0S3M3ZVJWRWtUbWJ1NktzWmtWMlp3RTBXN0puaHBOUDNCM3ZSYThNcmJvS2FOMWtocjhfYlJUMXg3R2dJUWFqT0NKdDJZaHV3VjA0M2lyX1FrV3cya01CUVJfS3FNZkstMHZaQ0QxcWV3SnNTSU5PbERYVEFkU01KV3EyY1JBNHVGdHRKdjY0bUxHazdUandUd3RLbFJzd2hDMWVkV3k3WDBfWE11MUVkLXEzYlF5Q29US1RDUnh0bmw3eWI0Mno1YXlCTmZFUWZiTHJKNHpRbnRUaHlQRjliQWx6SlJwMA==","email":"dseucan@enchoice.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCuOtVd3u1/Rati9gFlOVG5t7YCAZAvQ0RviI7I6feS2EF+pwk9Eym9rnVW/T9G6iUJyu9UIzZYBsEFF+4ZBgDGPqEB4geTOX9g0HIH+MLdBSspclDkp+KDU5EMCcJ7iPpsxqcKMgdKog/X2nUf4Ivlv8zwngSUpDYps98cKBMM3yKiFyuR+W4n5Apcj1AlY+iqVKC8nIc7mjwWHrsUk3BmiVsPull/qyKMyU75MFU0yCujx4TwLFwpCk1y1KR8wY9++vYvFEOeiwPcONJ6Q7aXGdZIMEmpI8o+YiWUDMiJMBUuyMUhIYAUvY6HeCEYvJ9sC3qd4Uq4OZpGyUbzdcyCfQJKm+oHi9D/YhHqp68+Mc39Y8Mdy2bYlFojlmk5LAHqS19WW+TFmS1s5h4SOiUbVoh2VS40ZRrKQinUMr4a457whf+Xv1ncLoQBh6H1zWMcy0BxIMmcPP3LkAIFjS8pI4RibnalDRQ9YmJQBGyVZ4mCVBjSQAaj1tQ4smYtOTfLOyeyY+12B1nU4hhnf1kCDu0+KPJRqOYCiO7HNr/Rk49wPwH7Yjm9SuFAAW1EFr33oHqFO/9p8FbbixhJDM0auxcaMmAs3SCLjA0Dt2jv4fGOGIfa4j330lAFJifnNMi+rWJ1+gVn3xl7O3lU94bbyeTstEZRENF9yOQ+MSBrVQ== ocpuser@OpenShift
